name: prod workflow

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  docker-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
          file_name: .env.local
          fail_on_empty: false

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build . -t octavianregatun/planitly-frontend-nextjs:dev

      - name: Docker push
        run: docker push octavianregatun/planitly-frontend-nextjs:dev